name: 'path condition'
description: 'Greet someone and record the time'
inputs:
  paths:  # id of input
    description: 'A YAML-string with named paths patterns'
    required: false
  paths-ignore:
    description: 'A YAML-string with named paths ignore patterns'
    required: false
outputs:
  should_skip:
    description: 'should skip this pull request'
  changed_files:
    description: 'changed files'
runs:
  using: 'node20'
  main: 'dist/index.js'
