name: 'Pull Request Path Filter'
description: 'Filter pull requests by changed file paths. A workaround for handling skipped but required status checks with path conditions.'
branding:
  icon: 'filter'
  color: 'blue'
inputs:
  paths:  # id of input
    description: 'A YAML-string with named paths patterns'
    required: false
  paths-ignore:
    description: 'A YAML-string with named paths ignore patterns'
    required: false
outputs:
  should_skip:
    description: 'should skip this pull request'
  changed_files:
    description: 'changed files'
runs:
  using: 'node24'
  main: 'dist/index.js'
