name: Sync Tags

on:
  push:
    tags:
      - 'v0.2.*'

permissions:
  contents: write

jobs:
  sync-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and push new tag
        if: startsWith(github.ref, 'refs/tags/v0.2.')
        run: |
            NEW_TAG="v0.2"
            git tag -f $NEW_TAG ${{ github.ref }}
            git push origin -f $NEW_TAG